// Sight word lists for the flashcard app.
// Edit freely: each level is a plain array of lowercase words.
// To add words the teacher sends home, paste them into the level you want, e.g. "because",
// Rules: lowercase only, no apostrophes, one word per entry. Order within a level is the
// "A to Z" order the app can show; by default the app shuffles.

const WORD_LEVELS = [
  {
    name: "Level 1",
    colour: "#3ec98a",
    // First sight words: the 200 most common words in English plus simple beginner words (Prep) (276 words)
    words: [
      "a", "about", "all", "am", "an", "and", "are", "as", "at", "be",
      "been", "but", "by", "called", "can", "come", "could", "day", "did", "do",
      "down", "each", "find", "first", "for", "from", "get", "go", "had", "has",
      "have", "he", "her", "him", "his", "how", "i", "if", "in", "into",
      "is", "it", "its", "like", "long", "look", "made", "make", "many", "may",
      "more", "my", "no", "not", "now", "number", "of", "on", "one", "or",
      "other", "out", "part", "people", "said", "see", "she", "so", "some", "than",
      "that", "the", "their", "them", "then", "there", "these", "they", "this", "time",
      "to", "two", "up", "use", "was", "water", "way", "we", "were", "what",
      "when", "which", "who", "will", "with", "words", "would", "write", "you", "your",
      "after", "again", "air", "also", "animal", "another", "answer", "any", "around", "ask",
      "away", "back", "because", "before", "big", "boy", "came", "change", "different", "does",
      "end", "even", "follow", "form", "found", "give", "good", "great", "hand", "help",
      "here", "home", "house", "just", "kind", "know", "land", "large", "learn", "letter",
      "line", "little", "live", "man", "me", "means", "men", "most", "mother", "move",
      "much", "must", "name", "need", "new", "off", "old", "only", "our", "over",
      "page", "picture", "place", "play", "point", "put", "read", "right", "same", "say",
      "sentence", "set", "should", "show", "small", "sound", "spell", "still", "study", "such",
      "take", "tell", "things", "think", "three", "through", "too", "try", "turn", "us",
      "very", "want", "well", "went", "where", "why", "work", "world", "years", "mum",
      "dad", "cat", "dog", "run", "jump", "funny", "yes", "red", "sit", "sun",
      "hat", "bed", "pig", "hen", "bus", "cup", "pen", "pet", "zoo", "bag",
      "bat", "bee", "bug", "cap", "fan", "fox", "hop", "hug", "jet", "leg",
      "lip", "log", "mud", "net", "nut", "pan", "pot", "rat", "rug", "sad",
      "tap", "tin", "tub", "van", "web", "wet", "dig", "jam", "kite", "bike",
      "cake", "chair", "coat", "cow", "doll", "duck", "egg", "flower", "rabbit", "sheep",
      "shoe", "toy", "bird", "seed", "nest", "boat", "ball", "box", "fish", "milk",
      "snow", "tree", "ride", "ate", "top", "book",
    ],
  },
  {
    name: "Level 2",
    colour: "#4a9bff",
    // Next 200 most common words plus Dolch grade-level words (Prep / Year 1) (272 words)
    words: [
      "above", "add", "almost", "along", "always", "began", "begin", "being", "below", "between",
      "both", "car", "carry", "children", "city", "close", "country", "cut", "earth", "eat",
      "enough", "every", "example", "eyes", "face", "family", "far", "father", "feet", "few",
      "food", "four", "girl", "got", "group", "grow", "hard", "head", "hear", "high",
      "idea", "important", "keep", "last", "late", "leave", "left", "let", "life", "light",
      "list", "might", "mile", "miss", "mountains", "near", "never", "next", "night", "often",
      "once", "open", "own", "paper", "plant", "real", "river", "saw", "school", "sea",
      "second", "seem", "side", "something", "sometimes", "song", "soon", "start", "state", "stop",
      "story", "talk", "those", "thought", "together", "took", "under", "until", "walk", "watch",
      "while", "white", "without", "young", "across", "against", "area", "become", "best", "better",
      "birds", "black", "body", "certain", "cold", "complete", "covered", "cried", "door", "draw",
      "during", "early", "easy", "ever", "fall", "farm", "fast", "field", "figure", "fire",
      "five", "friends", "ground", "happened", "heard", "himself", "hold", "horse", "hours", "however",
      "hundred", "king", "knew", "listen", "low", "map", "mark", "measure", "money", "morning",
      "music", "north", "notice", "order", "passed", "pattern", "piece", "plan", "problem", "products",
      "pulled", "questions", "reached", "remember", "rock", "room", "seen", "several", "ship", "short",
      "since", "sing", "slowly", "south", "space", "stand", "step", "sure", "table", "today",
      "told", "toward", "town", "travel", "true", "unit", "upon", "usually", "voice", "waves",
      "whole", "wind", "wood", "going", "thank", "call", "goes", "pull", "drink", "hurt",
      "laugh", "myself", "pick", "eight", "seven", "six", "ten", "pretty", "please", "bring",
      "clean", "done", "full", "hot", "shall", "warm", "green", "brown", "blue", "yellow",
      "purple", "orange", "pink", "happy", "love", "baby", "sleep", "party", "garden", "apple",
      "sister", "brother", "uncle", "teacher", "game", "fun", "bell", "cook", "park", "swim",
      "sand", "fruit", "meat", "rain", "moon", "sky", "wall", "window", "summer", "winter",
      "train", "road", "street", "hill", "lake", "ice", "gold", "hair", "floor", "bear",
      "hole", "tall", "quiet", "count", "jumped", "laughed", "smiled", "trip", "kept", "legs",
      "arms", "eggs", "flowers", "grass", "heart", "held", "job", "wish", "wild", "wide",
      "soft", "dance",
    ],
  },
  {
    name: "Level 3",
    colour: "#a66bff",
    // Fry words 401 to 700 (Year 1 / Year 2) (274 words)
    words: [
      "able", "ago", "among", "base", "became", "behind", "bread", "brought", "building", "built",
      "cannot", "carefully", "check", "circle", "class", "clear", "common", "contain", "correct", "course",
      "dark", "decided", "deep", "dry", "explain", "fact", "feel", "filled", "finally", "fine",
      "fly", "force", "front", "gave", "government", "half", "heat", "heavy", "inches", "include",
      "inside", "island", "known", "language", "less", "machine", "material", "minutes", "note", "nothing",
      "object", "ocean", "oh", "pair", "person", "plane", "power", "produce", "quickly", "ran",
      "rest", "round", "rule", "scientists", "shape", "shown", "size", "special", "stars", "stay",
      "stood", "strong", "surface", "system", "though", "thousands", "understand", "wait", "week", "wheels",
      "yet", "anything", "beautiful", "believe", "beside", "cause", "cells", "clothes", "describe", "developed",
      "difference", "direction", "discovered", "distance", "divided", "drive", "drop", "edge", "energy", "exercise",
      "farmers", "felt", "finished", "forest", "general", "gone", "instruments", "interest", "lay", "length",
      "main", "matter", "meet", "members", "million", "mind", "months", "paint", "past", "perhaps",
      "picked", "present", "probably", "race", "raised", "ready", "reason", "record", "region", "represent",
      "return", "root", "sat", "sign", "simple", "site", "square", "store", "subject", "suddenly",
      "sum", "test", "third", "weather", "west", "whether", "written", "act", "age", "already",
      "although", "amount", "angle", "appear", "beat", "bottom", "bright", "broken", "build", "buy",
      "care", "case", "century", "copy", "cross", "dictionary", "dress", "either", "everyone", "everything",
      "exactly", "fight", "fingers", "free", "hope", "instead", "iron", "lead", "lot", "melody",
      "metal", "method", "middle", "moment", "nation", "natural", "outside", "poor", "possible", "pounds",
      "pushed", "quite", "remain", "result", "rolled", "sail", "scale", "section", "soil", "solve",
      "someone", "son", "speak", "speed", "spring", "stone", "surprise", "temperature", "themselves", "tiny",
      "type", "village", "within", "wonder", "afternoon", "birthday", "cousin", "everybody", "favourite", "friend",
      "grandma", "grandpa", "holiday", "kitchen", "lunch", "nobody", "playground", "sandwich", "tonight", "weekend",
      "yesterday", "tomorrow", "breakfast", "dinner", "bedroom", "bathroom", "colour", "centre", "mummy", "daddy",
      "nanna", "aunty", "playing", "looking", "jumping", "running", "coming", "walking", "talking", "thinking",
      "wanted", "looked", "played", "stopped", "walked", "opened", "asked", "helped", "liked", "lived",
      "loved", "moved", "named", "needed", "used", "worked", "turned", "started", "eating", "reading",
      "writing", "sitting", "getting", "making",
    ],
  },
  {
    name: "Level 4",
    colour: "#ffb400",
    // Fry words 701 to 1000 (Year 2 and up) (280 words)
    words: [
      "alone", "art", "bad", "bank", "bit", "break", "business", "captain", "catch", "caught",
      "child", "choose", "climbed", "cloud", "coast", "continued", "control", "cool", "cost", "desert",
      "design", "direct", "drawing", "ears", "east", "else", "engine", "equal", "experiment", "express",
      "feeling", "fell", "flow", "foot", "gas", "glass", "grew", "history", "human", "increase",
      "information", "itself", "joined", "key", "lady", "law", "least", "lost", "maybe", "mouth",
      "pay", "period", "plains", "practice", "president", "received", "report", "ring", "rise", "row",
      "save", "seeds", "sent", "separate", "serve", "shouted", "single", "skin", "statement", "stick",
      "straight", "strange", "students", "suppose", "symbols", "team", "touch", "trouble", "valley", "visit",
      "wear", "whose", "wire", "woman", "wrote", "yard", "yourself", "addition", "belong", "block",
      "blow", "board", "bones", "branches", "cattle", "chief", "compare", "consider", "corner", "crops",
      "crowd", "current", "doctor", "dollars", "electric", "enjoy", "entered", "except", "exciting", "expect",
      "famous", "fit", "flat", "guess", "hit", "indicate", "industry", "insects", "interesting", "lie",
      "lifted", "loud", "major", "mine", "modern", "movement", "necessary", "observe", "particular", "planets",
      "poem", "pole", "position", "process", "property", "provide", "rather", "rhythm", "rich", "safe",
      "science", "sell", "send", "sense", "sharp", "shoulder", "sight", "silent", "spot", "spread",
      "stream", "string", "suggested", "supply", "terms", "thick", "thin", "tied", "tone", "trade",
      "tube", "value", "wash", "weight", "wife", "wings", "action", "actually", "afraid", "agreed",
      "ahead", "allow", "arrived", "born", "bought", "capital", "chance", "chart", "church", "column",
      "company", "conditions", "corn", "cotton", "cows", "create", "deal", "details", "determine", "difficult",
      "division", "effect", "entire", "especially", "evening", "experience", "factories", "fair", "fear", "forward",
      "fresh", "huge", "led", "level", "located", "march", "match", "northern", "nose", "office",
      "opposite", "prepared", "printed", "radio", "repeated", "rope", "rose", "score", "seat", "settled",
      "shoes", "shop", "similar", "smell", "solution", "southern", "steel", "stretched", "sugar", "tools",
      "total", "track", "triangle", "truck", "various", "view", "western", "win", "women", "workers",
      "wrong", "beginning", "computer", "dangerous", "decide", "disappear", "elephant", "everywhere", "excited", "fantastic",
      "forgot", "giant", "grandmother", "grandfather", "hospital", "hungry", "imagine", "jungle", "kangaroo", "koala",
      "library", "lightning", "magic", "mystery", "neighbour", "nervous", "penguin", "promise", "rescue", "scared",
      "secret", "shadow", "terrible", "thunder", "treasure", "umbrella", "vegetable", "whisper", "wonderful", "worried",
    ],
  },
];
